In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

e:\Python\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
data=pd.read_csv('Churn_Modelling.csv')

In [3]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

## Preprocessing

In [4]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [5]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  str
 2   Gender           10000 non-null  str
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), str(2)
memory usage: 966.1 KB

In [7]:
#Encodeing the categorical data

label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

from sklearn.preprocessing import OneHotEncoder
one_hot_encoder_geography=OneHotEncoder()
geo_encoded=one_hot_encoder_geography.fit_transform(data[['Geography']])
one_hot_encoder_geography.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [8]:
geo_encoded_df=pd.DataFrame(geo_encoded.toarray(),columns=one_hot_encoder_geography.get_feature_names_out(['Geography']))

In [9]:
## Combine

if 'Geography' in data.columns:
    data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
else:
    data = pd.concat([data, geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [10]:
## Save the Encoders and Scaler

In [11]:
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('one_hot_encoder_geography.pkl', 'wb') as file:
    pickle.dump(one_hot_encoder_geography, file)

In [12]:
## Divide dataset intto independent and dependent features

In [13]:
X=data.drop('Exited',axis=1)
y=data['Exited']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Scale the features
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [14]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

## TRAIN ANN MODEL

In [21]:
!python -m pip install tensorflow ipykernel
!python -m ipykernel install --user --name churn-venv --display-name "Churn venv"

Collecting tensorflow
  Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
Requirement already satisfied: ipykernel in e:\python\anaconda3\lib\site-packages (6.29.5)
Collecting absl-py>=1.0.0 (from tensorflow)
  Using cached absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in e:\python\anaconda3\lib\site-packages (from tensorflow) (24.2)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Downloading protobuf-7.35.0-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in e:\python\anaconda3\lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in e:\python\anaconda3\lib\site-packages (from tensorflow) (72.1.0)
Requirement already satisfied: six>=1.12.0 in e:\python\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in e:\python\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in e:\python\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.81.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting keras>=3.12.0 (from tensorflow)
  Downloading keras-3.14.1-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in e:\python\anaconda3\lib\site-packages (from tensorflow) (2.4.2)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in e:\python\anaconda3\lib\site-packages (from tensorflow) (3.12.1)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\python\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in e:\python\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\python\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in e:\python\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Requirement already satisfied: comm>=0.1.1 in e:\python\anaconda3\lib\site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: debugpy>=1.6.5 in e:\python\anaconda3\lib\site-packages (from ipykernel) (1.8.11)
Requirement already satisfied: ipython>=7.23.1 in e:\python\anaconda3\lib\site-packages (from ipykernel) (8.30.0)
Requirement already satisfied: jupyter-client>=6.1.12 in e:\python\anaconda3\lib\site-packages (from ipykernel) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in e:\python\anaconda3\lib\site-packages (from ipykernel) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in e:\python\anaconda3\lib\site-packages (from ipykernel) (0.1.6)
Requirement already satisfied: nest-asyncio in e:\python\anaconda3\lib\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: psutil in e:\python\anaconda3\lib\site-packages (from ipykernel) (5.9.0)
Requirement already satisfied: pyzmq>=24 in e:\python\anaconda3\lib\site-packages (from ipykernel) (26.2.0)
Requirement already satisfied: tornado>=6.1 in e:\python\anaconda3\lib\site-packages (from ipykernel) (6.5.1)
Requirement already satisfied: traitlets>=5.4.0 in e:\python\anaconda3\lib\site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in e:\python\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: decorator in e:\python\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (5.1.1)
Requirement already satisfied: jedi>=0.16 in e:\python\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.19.2)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in e:\python\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in e:\python\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (2.19.1)
Requirement already satisfied: stack-data in e:\python\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.2.0)
Requirement already satisfied: colorama in e:\python\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: wcwidth in e:\python\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in e:\python\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.4)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\python\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->ipykernel) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in e:\python\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (4.3.7)
Requirement already satisfied: pywin32>=300 in e:\python\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (308)
Requirement already satisfied: rich in e:\python\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (13.9.4)
Collecting namex (from keras>=3.12.0->tensorflow)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Downloading optree-0.19.1-cp313-cp313-win_amd64.whl.metadata (32 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in e:\python\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: mdurl~=0.1 in e:\python\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: executing in e:\python\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel) (0.8.3)
Requirement already satisfied: asttokens in e:\python\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel) (3.0.0)
Requirement already satisfied: pure-eval in e:\python\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel) (0.2.2)
Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl (351.2 MB)
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/351.2 MB ? eta -:--:--
   ---------------------------------------- 1.6/351.2 MB 6.4 MB/s eta 0:00:55
   ---------------------------------------- 2.4/351.2 MB 5.2 MB/s eta 0:01:07
   ---------------------------------------- 3.4/351.2 MB 4.7 MB/s eta 0:01:15
   ---------------------------------------- 4.2/351.2 MB 4.5 MB/s eta 0:01:17
    --------------------------------------- 5.0/351.2 MB 4.4 MB/s eta 0:01:19
    --------------------------------------- 5.8/351.2 MB 4.3 MB/s eta 0:01:21
    --------------------------------------- 6.6/351.2 MB 4.3 MB/s eta 0:01:21
    --------------------------------------- 7.6/351.2 MB 4.2 MB/s eta 0:01:22
    --------------------------------------- 8.4/351.2 MB 4.2 MB/s eta 0:01:23
   - -------------------------------------- 9.2/351.2 MB 4.1 MB/s eta 0:01:23
   - -------------------------------------- 10.0/351.2 MB 4.1 MB/s eta 0:01:23
   - -------------------------------------- 10.7/351.2 MB 4.1 MB/s eta 0:01:24
   - -------------------------------------- 11.5/351.2 MB 4.1 MB/s eta 0:01:24
   - -------------------------------------- 12.3/351.2 MB 4.1 MB/s eta 0:01:24
   - -------------------------------------- 13.4/351.2 MB 4.1 MB/s eta 0:01:24
   - -------------------------------------- 14.2/351.2 MB 4.0 MB/s eta 0:01:24
   - -------------------------------------- 14.9/351.2 MB 4.0 MB/s eta 0:01:24
   - -------------------------------------- 15.7/351.2 MB 4.0 MB/s eta 0:01:24
   - -------------------------------------- 16.5/351.2 MB 4.0 MB/s eta 0:01:24
   - -------------------------------------- 17.3/351.2 MB 4.0 MB/s eta 0:01:24
   -- ------------------------------------- 18.4/351.2 MB 4.0 MB/s eta 0:01:24
   -- ------------------------------------- 19.1/351.2 MB 4.0 MB/s eta 0:01:24
   -- ------------------------------------- 19.9/351.2 MB 4.0 MB/s eta 0:01:23
   -- ------------------------------------- 20.7/351.2 MB 4.0 MB/s eta 0:01:23
   -- ------------------------------------- 21.5/351.2 MB 4.0 MB/s eta 0:01:23
   -- ------------------------------------- 22.3/351.2 MB 4.0 MB/s eta 0:01:23
   -- ------------------------------------- 23.3/351.2 MB 4.0 MB/s eta 0:01:23
   -- ------------------------------------- 24.1/351.2 MB 4.0 MB/s eta 0:01:23
   -- ------------------------------------- 24.6/351.2 MB 4.0 MB/s eta 0:01:23
   -- ------------------------------------- 25.4/351.2 MB 3.9 MB/s eta 0:01:23
   -- ------------------------------------- 26.0/351.2 MB 3.9 MB/s eta 0:01:25
   --- ------------------------------------ 26.5/351.2 MB 3.8 MB/s eta 0:01:26
   --- ------------------------------------ 27.0/351.2 MB 3.8 MB/s eta 0:01:26
   --- ------------------------------------ 28.0/351.2 MB 3.8 MB/s eta 0:01:25
   --- ------------------------------------ 28.8/351.2 MB 3.8 MB/s eta 0:01:25
   --- ------------------------------------ 29.6/351.2 MB 3.8 MB/s eta 0:01:25
   --- ------------------------------------ 30.4/351.2 MB 3.8 MB/s eta 0:01:25
   --- ------------------------------------ 31.2/351.2 MB 3.8 MB/s eta 0:01:24
   --- ------------------------------------ 32.2/351.2 MB 3.8 MB/s eta 0:01:24
   --- ------------------------------------ 32.8/351.2 MB 3.8 MB/s eta 0:01:24
   --- ------------------------------------ 33.6/351.2 MB 3.8 MB/s eta 0:01:24
   --- ------------------------------------ 34.6/351.2 MB 3.8 MB/s eta 0:01:24
   ---- ----------------------------------- 35.4/351.2 MB 3.8 MB/s eta 0:01:23
   ---- ----------------------------------- 36.2/351.2 MB 3.8 MB/s eta 0:01:23
   ---- ----------------------------------- 37.0/351.2 MB 3.8 MB/s eta 0:01:23
   ---- ----------------------------------- 37.7/351.2 MB 3.8 MB/s eta 0:01:23
   ---- ----------------------------------- 38.5/351.2 MB 3.8 MB/s eta 0:01:22
   ---- ----------------------------------- 39.1/351.2 MB 3.8 MB/s eta 0:01:23
   ---- ----------------------------------- 39.6/351.2 MB 3.8 MB/s eta 0:01:23
   ---- ----------------------------------- 40.1/351.2 MB 3.7 MB/s eta 0:01:24
   ---- ----------------------------------- 40.9/351.2 MB 3.7 MB/s eta 0:01:24
   ---- ----------------------------------- 41.7/351.2 MB 3.7 MB/s eta 0:01:24
   ---- ----------------------------------- 42.2/351.2 MB 3.7 MB/s eta 0:01:24
   ---- ----------------------------------- 43.3/351.2 MB 3.7 MB/s eta 0:01:23
   ----- ---------------------------------- 44.0/351.2 MB 3.7 MB/s eta 0:01:23
   ----- ---------------------------------- 44.8/351.2 MB 3.7 MB/s eta 0:01:22
   ----- ---------------------------------- 45.9/351.2 MB 3.7 MB/s eta 0:01:22
   ----- ---------------------------------- 46.7/351.2 MB 3.7 MB/s eta 0:01:22
   ----- ---------------------------------- 47.4/351.2 MB 3.7 MB/s eta 0:01:22
   ----- ---------------------------------- 48.2/351.2 MB 3.7 MB/s eta 0:01:21
   ----- ---------------------------------- 49.0/351.2 MB 3.8 MB/s eta 0:01:21
   ----- ---------------------------------- 49.8/351.2 MB 3.8 MB/s eta 0:01:21
   ----- ---------------------------------- 50.9/351.2 MB 3.8 MB/s eta 0:01:20
   ----- ---------------------------------- 51.6/351.2 MB 3.8 MB/s eta 0:01:20
   ----- ---------------------------------- 52.4/351.2 MB 3.8 MB/s eta 0:01:20
   ------ --------------------------------- 53.2/351.2 MB 3.8 MB/s eta 0:01:20
   ------ --------------------------------- 54.0/351.2 MB 3.8 MB/s eta 0:01:19
   ------ --------------------------------- 54.8/351.2 MB 3.8 MB/s eta 0:01:19
   ------ --------------------------------- 55.6/351.2 MB 3.8 MB/s eta 0:01:19
   ------ --------------------------------- 56.4/351.2 MB 3.8 MB/s eta 0:01:19
   ------ --------------------------------- 57.4/351.2 MB 3.8 MB/s eta 0:01:18
   ------ --------------------------------- 58.2/351.2 MB 3.8 MB/s eta 0:01:18
   ------ --------------------------------- 58.7/351.2 MB 3.8 MB/s eta 0:01:18
   ------ --------------------------------- 59.8/351.2 MB 3.8 MB/s eta 0:01:18
   ------ --------------------------------- 60.6/351.2 MB 3.8 MB/s eta 0:01:17
   ------ --------------------------------- 61.3/351.2 MB 3.8 MB/s eta 0:01:17
   ------- -------------------------------- 62.1/351.2 MB 3.8 MB/s eta 0:01:17
   ------- -------------------------------- 63.2/351.2 MB 3.8 MB/s eta 0:01:17
   ------- -------------------------------- 64.0/351.2 MB 3.8 MB/s eta 0:01:16
   ------- -------------------------------- 64.7/351.2 MB 3.8 MB/s eta 0:01:16
   ------- -------------------------------- 65.5/351.2 MB 3.8 MB/s eta 0:01:16
   ------- -------------------------------- 66.3/351.2 MB 3.8 MB/s eta 0:01:16
   ------- -------------------------------- 67.1/351.2 MB 3.8 MB/s eta 0:01:16
   ------- -------------------------------- 67.9/351.2 MB 3.8 MB/s eta 0:01:15
   ------- -------------------------------- 68.9/351.2 MB 3.8 MB/s eta 0:01:15
   ------- -------------------------------- 69.7/351.2 MB 3.8 MB/s eta 0:01:15
   -------- ------------------------------- 70.5/351.2 MB 3.8 MB/s eta 0:01:15
   -------- ------------------------------- 71.3/351.2 MB 3.8 MB/s eta 0:01:14
   -------- ------------------------------- 72.1/351.2 MB 3.8 MB/s eta 0:01:14
   -------- ------------------------------- 72.9/351.2 MB 3.8 MB/s eta 0:01:14
   -------- ------------------------------- 73.7/351.2 MB 3.8 MB/s eta 0:01:14
   -------- ------------------------------- 74.4/351.2 MB 3.8 MB/s eta 0:01:13
   -------- ------------------------------- 75.5/351.2 MB 3.8 MB/s eta 0:01:13
   -------- ------------------------------- 76.3/351.2 MB 3.8 MB/s eta 0:01:13
   -------- ------------------------------- 77.1/351.2 MB 3.8 MB/s eta 0:01:13
   -------- ------------------------------- 77.9/351.2 MB 3.8 MB/s eta 0:01:12
   -------- ------------------------------- 78.6/351.2 MB 3.8 MB/s eta 0:01:12
   --------- ------------------------------ 79.4/351.2 MB 3.8 MB/s eta 0:01:12
   --------- ------------------------------ 80.5/351.2 MB 3.8 MB/s eta 0:01:12
   --------- ------------------------------ 81.3/351.2 MB 3.8 MB/s eta 0:01:11
   --------- ------------------------------ 81.5/351.2 MB 3.8 MB/s eta 0:01:11
   --------- ------------------------------ 82.6/351.2 MB 3.8 MB/s eta 0:01:11
   --------- ------------------------------ 83.1/351.2 MB 3.8 MB/s eta 0:01:11
   --------- ------------------------------ 83.6/351.2 MB 3.8 MB/s eta 0:01:11
   --------- ------------------------------ 84.4/351.2 MB 3.8 MB/s eta 0:01:11
   --------- ------------------------------ 85.2/351.2 MB 3.8 MB/s eta 0:01:11
   --------- ------------------------------ 85.7/351.2 MB 3.8 MB/s eta 0:01:11
   --------- ------------------------------ 86.5/351.2 MB 3.7 MB/s eta 0:01:11
   --------- ------------------------------ 87.0/351.2 MB 3.7 MB/s eta 0:01:11
   ---------- ----------------------------- 87.8/351.2 MB 3.7 MB/s eta 0:01:11
   ---------- ----------------------------- 88.3/351.2 MB 3.7 MB/s eta 0:01:11
   ---------- ----------------------------- 89.1/351.2 MB 3.7 MB/s eta 0:01:11
   ---------- ----------------------------- 89.9/351.2 MB 3.7 MB/s eta 0:01:11
   ---------- ----------------------------- 90.7/351.2 MB 3.7 MB/s eta 0:01:10
   ---------- ----------------------------- 91.8/351.2 MB 3.7 MB/s eta 0:01:10
   ---------- ----------------------------- 92.5/351.2 MB 3.7 MB/s eta 0:01:10
   ---------- ----------------------------- 93.3/351.2 MB 3.7 MB/s eta 0:01:10
   ---------- ----------------------------- 94.1/351.2 MB 3.7 MB/s eta 0:01:09
   ---------- ----------------------------- 94.9/351.2 MB 3.7 MB/s eta 0:01:09
   ---------- ----------------------------- 95.7/351.2 MB 3.7 MB/s eta 0:01:09
   ---------- ----------------------------- 96.5/351.2 MB 3.7 MB/s eta 0:01:09
   ----------- ---------------------------- 97.3/351.2 MB 3.7 MB/s eta 0:01:08
   ----------- ---------------------------- 98.3/351.2 MB 3.7 MB/s eta 0:01:08
   ----------- ---------------------------- 99.1/351.2 MB 3.7 MB/s eta 0:01:08
   ----------- ---------------------------- 99.9/351.2 MB 3.7 MB/s eta 0:01:08
   ----------- ---------------------------- 100.7/351.2 MB 3.7 MB/s eta 0:01:07
   ----------- ---------------------------- 101.4/351.2 MB 3.7 MB/s eta 0:01:07
   ----------- ---------------------------- 102.2/351.2 MB 3.7 MB/s eta 0:01:07
   ----------- ---------------------------- 103.0/351.2 MB 3.8 MB/s eta 0:01:07
   ----------- ---------------------------- 104.1/351.2 MB 3.8 MB/s eta 0:01:06
   ----------- ---------------------------- 104.9/351.2 MB 3.8 MB/s eta 0:01:06
   ------------ --------------------------- 105.6/351.2 MB 3.8 MB/s eta 0:01:06
   ------------ --------------------------- 106.4/351.2 MB 3.8 MB/s eta 0:01:06
   ------------ --------------------------- 107.2/351.2 MB 3.8 MB/s eta 0:01:05
   ------------ --------------------------- 108.3/351.2 MB 3.8 MB/s eta 0:01:05
   ------------ --------------------------- 109.1/351.2 MB 3.8 MB/s eta 0:01:05
   ------------ --------------------------- 109.8/351.2 MB 3.8 MB/s eta 0:01:05
   ------------ --------------------------- 110.6/351.2 MB 3.8 MB/s eta 0:01:05
   ------------ --------------------------- 111.4/351.2 MB 3.8 MB/s eta 0:01:04
   ------------ --------------------------- 112.2/351.2 MB 3.8 MB/s eta 0:01:04
   ------------ --------------------------- 113.0/351.2 MB 3.8 MB/s eta 0:01:04
   ------------ --------------------------- 114.0/351.2 MB 3.7 MB/s eta 0:01:04
   ------------- -------------------------- 114.8/351.2 MB 3.7 MB/s eta 0:01:04
   ------------- -------------------------- 115.6/351.2 MB 3.7 MB/s eta 0:01:03
   ------------- -------------------------- 116.4/351.2 MB 3.7 MB/s eta 0:01:03
   ------------- -------------------------- 117.2/351.2 MB 3.7 MB/s eta 0:01:03
   ------------- -------------------------- 118.0/351.2 MB 3.7 MB/s eta 0:01:03
   ------------- -------------------------- 118.8/351.2 MB 3.7 MB/s eta 0:01:03
   ------------- -------------------------- 119.5/351.2 MB 3.7 MB/s eta 0:01:02
   ------------- -------------------------- 120.6/351.2 MB 3.7 MB/s eta 0:01:02
   ------------- -------------------------- 121.1/351.2 MB 3.7 MB/s eta 0:01:02
   ------------- -------------------------- 122.2/351.2 MB 3.7 MB/s eta 0:01:02
   -------------- ------------------------- 122.9/351.2 MB 3.7 MB/s eta 0:01:01
   -------------- ------------------------- 123.7/351.2 MB 3.7 MB/s eta 0:01:01
   -------------- ------------------------- 124.5/351.2 MB 3.7 MB/s eta 0:01:01
   -------------- ------------------------- 125.3/351.2 MB 3.7 MB/s eta 0:01:01
   -------------- ------------------------- 126.1/351.2 MB 3.7 MB/s eta 0:01:01
   -------------- ------------------------- 126.9/351.2 MB 3.7 MB/s eta 0:01:00
   -------------- ------------------------- 127.7/351.2 MB 3.7 MB/s eta 0:01:00
   -------------- ------------------------- 128.5/351.2 MB 3.7 MB/s eta 0:01:00
   -------------- ------------------------- 129.2/351.2 MB 3.7 MB/s eta 0:01:00

WARNING: Ignoring invalid distribution ~atplotlib (e:\Python\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (e:\Python\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (e:\Python\anaconda3\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.45.1 requires pandas<3,>=1.4.0, but you have pandas 3.0.1 which is incompatible.
streamlit 1.45.1 requires protobuf<7,>=3.20, but you have protobuf 7.35.0 which is incompatible.

Installed kernelspec churn-venv in C:\Users\Abhishek dasila\AppData\Roaming\jupyter\kernels\churn-venv

In [41]:
!pip install tensorboard
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

Requirement already satisfied: tensorboard in e:\python\anaconda3\lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=0.4 in e:\python\anaconda3\lib\site-packages (from tensorboard) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in e:\python\anaconda3\lib\site-packages (from tensorboard) (1.81.0)
Requirement already satisfied: markdown>=2.6.8 in e:\python\anaconda3\lib\site-packages (from tensorboard) (3.8)
Requirement already satisfied: numpy>=1.12.0 in e:\python\anaconda3\lib\site-packages (from tensorboard) (2.4.2)
Requirement already satisfied: packaging in e:\python\anaconda3\lib\site-packages (from tensorboard) (24.2)
Requirement already satisfied: pillow in e:\python\anaconda3\lib\site-packages (from tensorboard) (11.1.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in e:\python\anaconda3\lib\site-packages (from tensorboard) (7.35.0)
Requirement already satisfied: setuptools>=41.0.0 in e:\python\anaconda3\lib\site-packages (from tensorboard) (72.1.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in e:\python\anaconda3\lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in e:\python\anaconda3\lib\site-packages (from tensorboard) (3.1.3)
Requirement already satisfied: typing-extensions~=4.12 in e:\python\anaconda3\lib\site-packages (from grpcio>=1.48.2->tensorboard) (4.15.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in e:\python\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.2)

WARNING: Ignoring invalid distribution ~atplotlib (E:\Python\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (E:\Python\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (E:\Python\anaconda3\Lib\site-packages)

In [42]:
X_train_scaled.shape

(8000, 12)

In [43]:
model=Sequential()
model.add(Dense(64,activation='relu',input_shape=(X_train_scaled.shape[1],)))
model.add(Dense(32,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.summary()

e:\Python\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [45]:
## Set up TenseorBoard

from tensorflow.keras.callbacks import TensorBoard,EarlyStopping
log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [46]:
## Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [47]:
history=model.fit(X_train_scaled,y_train,validation_data=(X_test_scaled,y_test),epochs=100,batch_size=32,callbacks=[tensorflow_callback,early_stopping_callback])

Epoch 1/100

250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8123 - loss: 0.4438 - val_accuracy: 0.8360 - val_loss: 0.3882
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8455 - loss: 0.3769 - val_accuracy: 0.8595 - val_loss: 0.3519
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8579 - loss: 0.3491 - val_accuracy: 0.8545 - val_loss: 0.3485
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8594 - loss: 0.3411 - val_accuracy: 0.8595 - val_loss: 0.3440
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8609 - loss: 0.3372 - val_accuracy: 0.8580 - val_loss: 0.3465
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8616 - loss: 0.3351 - val_accuracy: 0.8590 - val_loss: 0.3422
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8621 - loss: 0.3313 - val_accuracy: 0.8585 - val_loss: 0.3471
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8622 - loss: 0.3282 - val_accuracy: 0.8545 - val_loss: 0.3501
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8662 - loss: 0.3269 - val_accuracy: 0.8595 - val_loss: 0.3404
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8641 - loss: 0.3248 - val_accuracy: 0.8600 - val_loss: 0.3463
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8664 - loss: 0.3223 - val_accuracy: 0.8565 - val_loss: 0.3455
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8656 - loss: 0.3213 - val_accuracy: 0.8605 - val_loss: 0.3413
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8661 - loss: 0.3219 - val_accuracy: 0.8605 - val_loss: 0.3411
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8698 - loss: 0.3202 - val_accuracy: 0.8610 - val_loss: 0.3463
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8669 - loss: 0.3167 - val_accuracy: 0.8625 - val_loss: 0.3419
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8680 - loss: 0.3160 - val_accuracy: 0.8575 - val_loss: 0.3416
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8686 - loss: 0.3138 - val_accuracy: 0.8600 - val_loss: 0.3441
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8727 - loss: 0.3136 - val_accuracy: 0.8620 - val_loss: 0.3415
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8695 - loss: 0.3117 - val_accuracy: 0.8595 - val_loss: 0.3440

In [48]:
model.save('churn_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [56]:
## Load tensorboard extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [57]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6010 (pid 24236), started 0:00:26 ago. (Use '!kill 24236' to kill it.)

In [58]:
#Load the pickel file